server:
  port: 8502
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book?useSSL=false&serverTimezone=CST&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  ## Redis配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 8
        ## 连接池中的最小空闲连接
        min-idle: 0
    timeout: 1000

#----------打印日志----------
logging:
  level:
    com.yubo.web.mapper: info
#----------打印日志----------

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yubo.web.entity