server:
  port: 8502
spring:
  profiles:
    active: dev

#----------打印日志----------
logging:
  level:
    com.yubo.web.mapper: info
#----------打印日志----------

#----------Http连接池配置----------
http:
  #最大连接数
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
#----------Http连接池配置----------